FROM python:3.11-slim

WORKDIR /app

COPY token_api.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5001

CMD ["uvicorn", "token_api:app", "--host", "0.0.0.0", "--port", "5001"]