api:
  url: ${API_URL}
  token_url: ${TOKEN_API_URL}
tools:
  manufacturing:
    type: api
    minio:
      bucket: manufacturing-data
      sop_prefix: sop-pdfs/
      mes_logs_prefix: mes-logs/
    qdrant:
      collections: ["sop_cache"]
      sop_cache_ttl: 36000
    api_endpoint: /machines/
  human_resources:
    type: api
    minio:
      bucket: human-resources-data
      sop_prefix: hr-pdfs/
      mes_logs_prefix: hr-logs/
    qdrant:
      collections: ["sop_cache"]
      sop_cache_ttl: 36000
    api_endpoint: /employees/
