data_source:
  use_minio_logs: false  # true: datos desde MinIO, false: datos desde API
api:
  url: ${API_URL}
  token_url: ${TOKEN_API_URL}
minio:
  bucket: sop-pdfs
  mes_logs_bucket: mes-logs
qdrant:
  collections: ["mes_logs", "sop_pdfs", "mes_json_logs"]