data_source:
  use_minio_logs: false  # true: datos desde MinIO, false: datos desde API
api:
  url: http://api:5000
  token_url: http://token-api:5001
minio:
  bucket: sop-pdfs
  mes_logs_bucket: mes-logs
qdrant:
  collections:
    - mes_logs
    - sop_pdfs
    - custom_rules
    - mes_json_logs