data_source:
  use_minio_logs: false  # true: datos desde MinIO, false: datos desde API
api:
  url: ${API_URL}
  token_url: ${TOKEN_API_URL}
minio:
  bucket: sop-pdfs
  mes_logs_bucket: mes-logs
pdf_extraction:
  identifier_fields: ["machine"]  # Campos que forman el identifier (por ejemplo, ["machine"] o ["machine", "production_line"])
  pdf_name_template: "{identifier}.pdf"  # Plantilla para el nombre del PDF
  cache_time: 10800