data_source:
  use_minio_logs: false  # true: datos desde MinIO, false: datos desde API
api:
  url: ${API_URL}
  token_url: ${TOKEN_API_URL}
minio:
  sop_prefix: sop-pdfs/
  mes_logs_prefix: mes-logs/
qdrant:
  collections: ["sop_cache"]  # Solo una colección para la caché de SOPs
  sop_cache_ttl: 36000  # Tiempo de vida de la caché en segundos (1 hora por defecto)